---
title: Rocket
hero_image: images/banner.png
description: Create a model of a rocket using Blender
theme: синій #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, дизайн -1, програмування-0, phys-comp-0, виробництво-0, спільнота-0
interests: space, art
technologies: blender
site_areas: projects
hardware: ''
software: blender
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: З днем народження
  - 
    title: Що вам знадобиться
  - 
    title: Base of the rocket
  - 
    title: Body of the rocket
  - 
    title: Nose cone
  - 
    title: Colour the rocket
  - 
    title: Add stripes
  - 
    title: Red nose
  - 
    title: "Challenge: more colour"
