---
title: Rocket
hero_image: images/banner.png
description: Create a model of a rocket using Blender
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: space, art
technologies: blender
site_areas: projects
hardware: ''
software: blender
version: 4
last_tested: 2020-01-29
steps:
- title: What you will make
- title: Base of the rocket
  completion:
  - engaged
- title: Body of the rocket
- title: Nose cone
- title: Colour the rocket
- title: Add stripes
  completion:
  - internal
- title: Challenge
  challenge: true
- title: What can you do now?
  completion:
  - external
