---
title: राकेट
hero_image: images/banner.png
description: Blender का उपयोग करके एक रॉकेट का मॉडल बनाएँ!
theme: नीला #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: creator, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: अंतरिक्ष, कला
technologies: blender (ब्लेंडर)
site_areas: प्रोजेक्ट
hardware: ''
software: blender
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: भूमिका
  - 
    title: आपको किसकी ज़रूरत होगी
  - 
    title: रॉकेट का आधार
  - 
    title: रॉकेट की बॉडी
  - 
    title: नाक शंकु
  - 
    title: रॉकेट में रंग भरें
  - 
    title: पट्टियाँ जोड़ें
  - 
    title: लाल नाक
  - 
    title: "चुनौती: अधिक रंग"
