---
title: Rocket
hero_image: images/banner.png
description: Create a model of a rocket using Blender
theme: sininen #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: space, art
technologies: blender
site_areas: projektit
hardware: ''
software: blender
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Johdanto
  - 
    title: Mitä tarvitset
  - 
    title: Base of the rocket
  - 
    title: Body of the rocket
  - 
    title: Nose cone
  - 
    title: Colour the rocket
  - 
    title: Add stripes
  - 
    title: Red nose
  - 
    title: "Challenge: more colour"
