---
title: Rocket
hero_image: images/banner.png
description: Create a model of a rocket using Blender
theme: blue #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1，design-1，programming-0，phys-comp-0，manufacture-0，community-0
interests: space, art
technologies: 攪拌器
site_areas: projects
hardware: ''
software: 攪拌器
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: 介紹
  - 
    title: 你會需要
  - 
    title: Base of the rocket
  - 
    title: Body of the rocket
  - 
    title: Nose cone
  - 
    title: Colour the rocket
  - 
    title: Add stripes
  - 
    title: Red nose
  - 
    title: "Challenge: more colour"
