---
title: Cohete
hero_image: images/banner.png
description: Crea un modelo de cohete con Blender
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: space, art
technologies: blender
site_areas: projects
hardware: ''
software: blender
version: 4
last_tested: 2020-01-29
steps:
- title: Introducción
  completion: engaged
- title: Base del cohete
- title: Cuerpo del cohete
- title: Cono de la nariz
- title: Colorea el cohete
- title: Agrega rayas
- title: Nariz roja
  completion: internal
- title: 'Desafío: Más colores'
